rmcs_location:
  ros__parameters:
    initialize_pose: true
    localization_when_lost: true
    path_map: "/workspaces/sentry/rmcs_ws/bag/standard.pcd"
    registration_size: 5000
    lidar_to_odom:
      AngleAxis:
        x: 0.0
        y: 3.1415926535897932384626433832795028841971693993751058209749445923078164
        z: 0.0
      Translation:
        x: 0.0
        y: 0.0
        z: 0.0

rmcs_location_test:
  ros__parameters:
    path_map: "/workspaces/sentry/ignore/develop_ws/pcd/standard.pcd"
    path_scan: "/workspaces/sentry/ignore/bag/robomaster_slam.pcd"

rmcs_location_gicp:
  ros__parameters:
    gicp:
      maximum_iterations_detailed: 500
      maximum_iterations_rough: 100
      distance_threshold: 5.
      transformation_epsilon: 0.000001
      euclidean_fitness_epsilon: 0.000001
      threads: 10
      # recommend scan angle: 20
      # search outwards with a given angle as the center 
      # and [scan_angle] as the step length
      scan_angle: 20
      # recommend score threshold: 0.03
      # this value is optimal given the real size of the battlefield
      score_threshold: 0.03
    outlier_removal:
      mean_k: 50
      stddev_mul_thresh: 0.5
    voxel_grid:
      lx: 0.2
      ly: 0.2
      lz: 0.2